dtmc

// Constant for the fail state of a module
const int fail = 0;

// Constant for the success state of a module
const int success = 1;

const int fakeStart = 2;

module whoisOperation_Database__databasePC_Provided_DatabaseInterface
	s_whoisOperation_Database__databasePC_Provided_DatabaseInterface:[0..5] init fakeStart;
	// Transition to start module when invoked by node 4 from module whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface
	[call_whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface_4_whoisOperation_Database__databasePC_Provided_DatabaseInterface] s_whoisOperation_Database__databasePC_Provided_DatabaseInterface = fakeStart -> 
		1:(s_whoisOperation_Database__databasePC_Provided_DatabaseInterface' = 5);
	// Transition to synchronize the successful return when invoked by node 4 from module whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface
	[ret_whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface_4_whoisOperation_Database__databasePC_Provided_DatabaseInterface] s_whoisOperation_Database__databasePC_Provided_DatabaseInterface = success -> 
		1:(s_whoisOperation_Database__databasePC_Provided_DatabaseInterface' = fakeStart);
	// Transition to synchronize the fail return when invoked by node 4 from module whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface
	[ret_whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface_4_whoisOperation_Database__databasePC_Provided_DatabaseInterface] s_whoisOperation_Database__databasePC_Provided_DatabaseInterface = fail -> 
		1:(s_whoisOperation_Database__databasePC_Provided_DatabaseInterface' = fail);
	
	// Transitions from node start :
	// 
	[]s_whoisOperation_Database__databasePC_Provided_DatabaseInterface = 5 ->
		1.0:(s_whoisOperation_Database__databasePC_Provided_DatabaseInterface' = 3);



	// Transitions from node internal :
	// 
	[]s_whoisOperation_Database__databasePC_Provided_DatabaseInterface = 3 ->
		1.0:(s_whoisOperation_Database__databasePC_Provided_DatabaseInterface' = 4);



	// Transition from end node end to success
	[] s_whoisOperation_Database__databasePC_Provided_DatabaseInterface = 4 -> 1:(s_whoisOperation_Database__databasePC_Provided_DatabaseInterface' = success);
	// Transition to fix deadlocks on fake start state
	[] s_whoisOperation_Database__databasePC_Provided_DatabaseInterface = fakeStart -> 1:(s_whoisOperation_Database__databasePC_Provided_DatabaseInterface' = fakeStart);
	
	// Transition to fix deadlocks on fail state
	[] s_whoisOperation_Database__databasePC_Provided_DatabaseInterface = fail -> 1:(s_whoisOperation_Database__databasePC_Provided_DatabaseInterface' = fail);

endmodule

module whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface
	s_whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface:[0..6] init fakeStart;
	// Transition to start module when invoked by node 4 from module whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface
	[call_whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface_4_whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface] s_whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface = fakeStart -> 
		1:(s_whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface' = 3);
	// Transition to synchronize the successful return when invoked by node 4 from module whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface
	[ret_whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface_4_whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface] s_whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface = success -> 
		1:(s_whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface' = fakeStart);
	// Transition to synchronize the fail return when invoked by node 4 from module whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface
	[ret_whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface_4_whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface] s_whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface = fail -> 
		1:(s_whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface' = fail);
	
	// Transitions from node  :
	// 
	[]s_whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface = 3 ->
		1.0:(s_whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface' = 4);




	// Invocation transition to module whoisOperation_Database__databasePC_Provided_DatabaseInterface
	[call_whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface_4_whoisOperation_Database__databasePC_Provided_DatabaseInterface] s_whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface = 4 -> 
		1:(s_whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface' = 6);
	// Success return transition from module whoisOperation_Database__databasePC_Provided_DatabaseInterface
	[ret_whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface_4_whoisOperation_Database__databasePC_Provided_DatabaseInterface] s_whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface = 6 & s_whoisOperation_Database__databasePC_Provided_DatabaseInterface = success -> 
		1:(s_whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface' = 5);
	// Fail return transition from module whoisOperation_Database__databasePC_Provided_DatabaseInterface
	[ret_whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface_4_whoisOperation_Database__databasePC_Provided_DatabaseInterface] s_whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface = 6 & s_whoisOperation_Database__databasePC_Provided_DatabaseInterface = fail -> 
		1:(s_whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface' = fail);


	// Transition from end node  to success
	[] s_whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface = 5 -> 1:(s_whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface' = success);
	// Transition to fix deadlocks on fake start state
	[] s_whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface = fakeStart -> 1:(s_whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface' = fakeStart);
	
	// Transition to fix deadlocks on fail state
	[] s_whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface = fail -> 1:(s_whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface' = fail);

endmodule

module whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface
	s_whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface:[0..6] init fakeStart;
	// Transition to start module when invoked by node 3 from module whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface
	[call_whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface_3_whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface] s_whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface = fakeStart -> 
		1:(s_whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface' = 3);
	// Transition to synchronize the successful return when invoked by node 3 from module whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface
	[ret_whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface_3_whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface] s_whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface = success -> 
		1:(s_whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface' = fakeStart);
	// Transition to synchronize the fail return when invoked by node 3 from module whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface
	[ret_whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface_3_whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface] s_whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface = fail -> 
		1:(s_whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface' = fail);
	
	// Transitions from node  :
	// 
	[]s_whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface = 3 ->
		1.0:(s_whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface' = 4);




	// Invocation transition to module whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface
	[call_whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface_4_whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface] s_whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface = 4 -> 
		1:(s_whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface' = 6);
	// Success return transition from module whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface
	[ret_whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface_4_whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface] s_whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface = 6 & s_whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface = success -> 
		1:(s_whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface' = 5);
	// Fail return transition from module whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface
	[ret_whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface_4_whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface] s_whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface = 6 & s_whoisOperation_Database__ServiceComposite_Required_DatabaseInterface__join__databasePC_Provided_DatabaseInterface = fail -> 
		1:(s_whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface' = fail);


	// Transition from end node  to success
	[] s_whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface = 5 -> 1:(s_whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface' = success);
	// Transition to fix deadlocks on fake start state
	[] s_whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface = fakeStart -> 1:(s_whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface' = fakeStart);
	
	// Transition to fix deadlocks on fail state
	[] s_whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface = fail -> 1:(s_whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface' = fail);

endmodule

module whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface
	s_whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface:[0..6] init fakeStart;
	// Transition to start module when invoked by node 4 from module whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface
	[call_whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface_4_whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface] s_whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface = fakeStart -> 
		1:(s_whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface' = 5);
	// Transition to synchronize the successful return when invoked by node 4 from module whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface
	[ret_whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface_4_whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface] s_whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface = success -> 
		1:(s_whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface' = fakeStart);
	// Transition to synchronize the fail return when invoked by node 4 from module whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface
	[ret_whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface_4_whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface] s_whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface = fail -> 
		1:(s_whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface' = fail);
	
	// Transitions from node start :
	// 
	[]s_whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface = 5 ->
		1.0:(s_whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface' = 3);




	// Invocation transition to module whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface
	[call_whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface_3_whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface] s_whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface = 3 -> 
		1:(s_whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface' = 6);
	// Success return transition from module whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface
	[ret_whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface_3_whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface] s_whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface = 6 & s_whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface = success -> 
		1:(s_whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface' = 4);
	// Fail return transition from module whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface
	[ret_whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface_3_whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface] s_whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface = 6 & s_whoisOperation_Database__DatabaseManagerPC_Required_DatabaseInterface__join__ServiceComposite_Required_DatabaseInterface = fail -> 
		1:(s_whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface' = fail);


	// Transition from end node end to success
	[] s_whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface = 4 -> 1:(s_whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface' = success);
	// Transition to fix deadlocks on fake start state
	[] s_whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface = fakeStart -> 1:(s_whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface' = fakeStart);
	
	// Transition to fix deadlocks on fail state
	[] s_whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface = fail -> 1:(s_whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface' = fail);

endmodule

module whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface
	s_whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface:[0..6] init fakeStart;
	// Transition to start module when invoked by node 3 from module nested12637b4
	[call_nested12637b4_3_whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface] s_whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface = fakeStart -> 
		1:(s_whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface' = 3);
	// Transition to synchronize the successful return when invoked by node 3 from module nested12637b4
	[ret_nested12637b4_3_whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface] s_whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface = success -> 
		1:(s_whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface' = fakeStart);
	// Transition to synchronize the fail return when invoked by node 3 from module nested12637b4
	[ret_nested12637b4_3_whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface] s_whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface = fail -> 
		1:(s_whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface' = fail);
	
	// Transitions from node  :
	// 
	[]s_whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface = 3 ->
		1.0:(s_whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface' = 4);




	// Invocation transition to module whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface
	[call_whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface_4_whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface] s_whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface = 4 -> 
		1:(s_whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface' = 6);
	// Success return transition from module whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface
	[ret_whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface_4_whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface] s_whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface = 6 & s_whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface = success -> 
		1:(s_whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface' = 5);
	// Fail return transition from module whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface
	[ret_whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface_4_whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface] s_whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface = 6 & s_whoisOperation_DatabaseManager__DatabaseManagerPC_Provided_DatabaseManagerInterface = fail -> 
		1:(s_whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface' = fail);


	// Transition from end node  to success
	[] s_whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface = 5 -> 1:(s_whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface' = success);
	// Transition to fix deadlocks on fake start state
	[] s_whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface = fakeStart -> 1:(s_whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface' = fakeStart);
	
	// Transition to fix deadlocks on fail state
	[] s_whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface = fail -> 1:(s_whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface' = fail);

endmodule

module nested12637b4
	s_nested12637b4:[0..7] init fakeStart;
	// Transition to start module when invoked by node 7 from module whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface
	[call_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface_7_nested12637b4] s_nested12637b4 = fakeStart -> 
		1:(s_nested12637b4' = 6);
	// Transition to synchronize the successful return when invoked by node 7 from module whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface
	[ret_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface_7_nested12637b4] s_nested12637b4 = success -> 
		1:(s_nested12637b4' = fakeStart);
	// Transition to synchronize the fail return when invoked by node 7 from module whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface
	[ret_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface_7_nested12637b4] s_nested12637b4 = fail -> 
		1:(s_nested12637b4' = fail);
	
	// Transitions from node start :
	// 
	[]s_nested12637b4 = 6 ->
		1.0:(s_nested12637b4' = 5);




	// Invocation transition to module whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface
	[call_nested12637b4_3_whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface] s_nested12637b4 = 3 -> 
		1:(s_nested12637b4' = 7);
	// Success return transition from module whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface
	[ret_nested12637b4_3_whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface] s_nested12637b4 = 7 & s_whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface = success -> 
		1:(s_nested12637b4' = 4);
	// Fail return transition from module whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface
	[ret_nested12637b4_3_whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface] s_nested12637b4 = 7 & s_whoisOperation_DatabaseManager__dataServicePC_Required_DatabaseManagerInterface__join__DatabaseManagerPC_Provided_DatabaseManagerInterface = fail -> 
		1:(s_nested12637b4' = fail);

	// Transitions from node internal :
	// 
	[]s_nested12637b4 = 5 ->
		0.9:(s_nested12637b4' = 3) + 
		0.09999999999999998:(s_nested12637b4' = fail);


	// Transition from end node end to success
	[] s_nested12637b4 = 4 -> 1:(s_nested12637b4' = success);
	// Transition to fix deadlocks on fake start state
	[] s_nested12637b4 = fakeStart -> 1:(s_nested12637b4' = fakeStart);
	
	// Transition to fix deadlocks on fail state
	[] s_nested12637b4 = fail -> 1:(s_nested12637b4' = fail);

endmodule

module nesteda7eb3f
	s_nesteda7eb3f:[0..5] init fakeStart;
	// Transition to start module when invoked by node 8 from module whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface
	[call_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface_8_nesteda7eb3f] s_nesteda7eb3f = fakeStart -> 
		1:(s_nesteda7eb3f' = 5);
	// Transition to synchronize the successful return when invoked by node 8 from module whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface
	[ret_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface_8_nesteda7eb3f] s_nesteda7eb3f = success -> 
		1:(s_nesteda7eb3f' = fakeStart);
	// Transition to synchronize the fail return when invoked by node 8 from module whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface
	[ret_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface_8_nesteda7eb3f] s_nesteda7eb3f = fail -> 
		1:(s_nesteda7eb3f' = fail);
	
	// Transitions from node start :
	// 
	[]s_nesteda7eb3f = 5 ->
		1.0:(s_nesteda7eb3f' = 4);




	// Transitions from node internal :
	// 
	[]s_nesteda7eb3f = 4 ->
		1.0:(s_nesteda7eb3f' = 3);


	// Transition from end node end to success
	[] s_nesteda7eb3f = 3 -> 1:(s_nesteda7eb3f' = success);
	// Transition to fix deadlocks on fake start state
	[] s_nesteda7eb3f = fakeStart -> 1:(s_nesteda7eb3f' = fakeStart);
	
	// Transition to fix deadlocks on fail state
	[] s_nesteda7eb3f = fail -> 1:(s_nesteda7eb3f' = fail);

endmodule

module whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface
	s_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface:[0..10] init fakeStart;
	// Transition to start module when invoked by node 4 from module whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface
	[call_whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface_4_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface] s_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface = fakeStart -> 
		1:(s_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface' = 5);
	// Transition to synchronize the successful return when invoked by node 4 from module whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface
	[ret_whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface_4_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface] s_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface = success -> 
		1:(s_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface' = fakeStart);
	// Transition to synchronize the fail return when invoked by node 4 from module whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface
	[ret_whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface_4_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface] s_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface = fail -> 
		1:(s_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface' = fail);
	
	// Transitions from node start :
	// 
	[]s_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface = 5 ->
		1.0:(s_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface' = 4);




	// Transitions from node branch :
	// 
	[]s_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface = 4 ->
		0.4:(s_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface' = 7) + 
		0.6:(s_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface' = 8);

	// Transitions from node join :
	// 
	[]s_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface = 6 ->
		1.0:(s_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface' = 3);


	// Invocation transition to module nested12637b4
	[call_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface_7_nested12637b4] s_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface = 7 -> 
		1:(s_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface' = 9);
	// Success return transition from module nested12637b4
	[ret_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface_7_nested12637b4] s_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface = 9 & s_nested12637b4 = success -> 
		1:(s_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface' = 6);
	// Fail return transition from module nested12637b4
	[ret_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface_7_nested12637b4] s_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface = 9 & s_nested12637b4 = fail -> 
		1:(s_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface' = fail);

	// Invocation transition to module nesteda7eb3f
	[call_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface_8_nesteda7eb3f] s_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface = 8 -> 
		1:(s_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface' = 10);
	// Success return transition from module nesteda7eb3f
	[ret_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface_8_nesteda7eb3f] s_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface = 10 & s_nesteda7eb3f = success -> 
		1:(s_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface' = 6);
	// Fail return transition from module nesteda7eb3f
	[ret_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface_8_nesteda7eb3f] s_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface = 10 & s_nesteda7eb3f = fail -> 
		1:(s_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface' = fail);

	// Transition from end node end to success
	[] s_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface = 3 -> 1:(s_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface' = success);
	// Transition to fix deadlocks on fake start state
	[] s_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface = fakeStart -> 1:(s_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface' = fakeStart);
	
	// Transition to fix deadlocks on fail state
	[] s_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface = fail -> 1:(s_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface' = fail);

endmodule

module whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface
	s_whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface:[0..6] init fakeStart;
	// Transition to start module when invoked by node 4 from module whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface
	[call_whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface_4_whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface] s_whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface = fakeStart -> 
		1:(s_whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface' = 3);
	// Transition to synchronize the successful return when invoked by node 4 from module whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface
	[ret_whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface_4_whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface] s_whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface = success -> 
		1:(s_whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface' = fakeStart);
	// Transition to synchronize the fail return when invoked by node 4 from module whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface
	[ret_whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface_4_whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface] s_whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface = fail -> 
		1:(s_whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface' = fail);
	
	// Transitions from node  :
	// 
	[]s_whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface = 3 ->
		1.0:(s_whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface' = 4);




	// Invocation transition to module whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface
	[call_whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface_4_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface] s_whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface = 4 -> 
		1:(s_whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface' = 6);
	// Success return transition from module whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface
	[ret_whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface_4_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface] s_whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface = 6 & s_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface = success -> 
		1:(s_whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface' = 5);
	// Fail return transition from module whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface
	[ret_whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface_4_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface] s_whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface = 6 & s_whoisOperation_DataService__dataServicePC_Provided_DataServiceInterface = fail -> 
		1:(s_whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface' = fail);


	// Transition from end node  to success
	[] s_whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface = 5 -> 1:(s_whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface' = success);
	// Transition to fix deadlocks on fake start state
	[] s_whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface = fakeStart -> 1:(s_whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface' = fakeStart);
	
	// Transition to fix deadlocks on fail state
	[] s_whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface = fail -> 1:(s_whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface' = fail);

endmodule

module whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface
	s_whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface:[0..6] init fakeStart;
	// Transition to start module when invoked by node 4 from module whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface
	[call_whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface_4_whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface] s_whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface = fakeStart -> 
		1:(s_whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface' = 3);
	// Transition to synchronize the successful return when invoked by node 4 from module whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface
	[ret_whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface_4_whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface] s_whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface = success -> 
		1:(s_whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface' = fakeStart);
	// Transition to synchronize the fail return when invoked by node 4 from module whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface
	[ret_whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface_4_whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface] s_whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface = fail -> 
		1:(s_whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface' = fail);
	
	// Transitions from node  :
	// 
	[]s_whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface = 3 ->
		1.0:(s_whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface' = 4);




	// Invocation transition to module whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface
	[call_whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface_4_whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface] s_whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface = 4 -> 
		1:(s_whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface' = 6);
	// Success return transition from module whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface
	[ret_whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface_4_whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface] s_whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface = 6 & s_whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface = success -> 
		1:(s_whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface' = 5);
	// Fail return transition from module whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface
	[ret_whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface_4_whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface] s_whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface = 6 & s_whoisOperation_DataService__ServerComposite_Provided_DataServiceInterface__join__dataServicePC_Provided_DataServiceInterface = fail -> 
		1:(s_whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface' = fail);


	// Transition from end node  to success
	[] s_whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface = 5 -> 1:(s_whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface' = success);
	// Transition to fix deadlocks on fake start state
	[] s_whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface = fakeStart -> 1:(s_whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface' = fakeStart);
	
	// Transition to fix deadlocks on fail state
	[] s_whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface = fail -> 1:(s_whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface' = fail);

endmodule

module whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface
	s_whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface:[0..6] init fakeStart;
	// Transition to start module when invoked by node 4 from module whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface
	[call_whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface_4_whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface] s_whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface = fakeStart -> 
		1:(s_whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface' = 3);
	// Transition to synchronize the successful return when invoked by node 4 from module whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface
	[ret_whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface_4_whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface] s_whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface = success -> 
		1:(s_whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface' = fakeStart);
	// Transition to synchronize the fail return when invoked by node 4 from module whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface
	[ret_whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface_4_whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface] s_whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface = fail -> 
		1:(s_whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface' = fail);
	
	// Transitions from node  :
	// 
	[]s_whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface = 3 ->
		1.0:(s_whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface' = 4);




	// Invocation transition to module whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface
	[call_whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface_4_whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface] s_whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface = 4 -> 
		1:(s_whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface' = 6);
	// Success return transition from module whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface
	[ret_whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface_4_whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface] s_whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface = 6 & s_whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface = success -> 
		1:(s_whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface' = 5);
	// Fail return transition from module whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface
	[ret_whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface_4_whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface] s_whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface = 6 & s_whoisOperation_DataService__clientComposite_Required_DataServiceInterface__join__ServerComposite_Provided_DataServiceInterface = fail -> 
		1:(s_whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface' = fail);


	// Transition from end node  to success
	[] s_whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface = 5 -> 1:(s_whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface' = success);
	// Transition to fix deadlocks on fake start state
	[] s_whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface = fakeStart -> 1:(s_whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface' = fakeStart);
	
	// Transition to fix deadlocks on fail state
	[] s_whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface = fail -> 1:(s_whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface' = fail);

endmodule

module whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface
	s_whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface:[0..6] init fakeStart;
	// Transition to start module when invoked by node 4 from module whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface
	[call_whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface_4_whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface] s_whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface = fakeStart -> 
		1:(s_whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface' = 5);
	// Transition to synchronize the successful return when invoked by node 4 from module whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface
	[ret_whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface_4_whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface] s_whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface = success -> 
		1:(s_whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface' = fakeStart);
	// Transition to synchronize the fail return when invoked by node 4 from module whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface
	[ret_whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface_4_whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface] s_whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface = fail -> 
		1:(s_whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface' = fail);
	
	// Transitions from node start :
	// 
	[]s_whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface = 5 ->
		1.0:(s_whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface' = 4);





	// Invocation transition to module whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface
	[call_whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface_4_whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface] s_whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface = 4 -> 
		1:(s_whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface' = 6);
	// Success return transition from module whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface
	[ret_whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface_4_whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface] s_whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface = 6 & s_whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface = success -> 
		1:(s_whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface' = 3);
	// Fail return transition from module whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface
	[ret_whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface_4_whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface] s_whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface = 6 & s_whoisOperation_DataService__dataRetrieverPC_Required_DataServiceInterface__join__clientComposite_Required_DataServiceInterface = fail -> 
		1:(s_whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface' = fail);

	// Transition from end node end to success
	[] s_whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface = 3 -> 1:(s_whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface' = success);
	// Transition to fix deadlocks on fake start state
	[] s_whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface = fakeStart -> 1:(s_whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface' = fakeStart);
	
	// Transition to fix deadlocks on fail state
	[] s_whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface = fail -> 1:(s_whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface' = fail);

endmodule

module whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface
	s_whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface:[0..6] init fakeStart;
	// Transition to start module when invoked by node 4 from module whoisOperation_GuiInterface__guiComponentPC_Provided_GuiInterface
	[call_whoisOperation_GuiInterface__guiComponentPC_Provided_GuiInterface_4_whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface] s_whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface = fakeStart -> 
		1:(s_whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface' = 3);
	// Transition to synchronize the successful return when invoked by node 4 from module whoisOperation_GuiInterface__guiComponentPC_Provided_GuiInterface
	[ret_whoisOperation_GuiInterface__guiComponentPC_Provided_GuiInterface_4_whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface] s_whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface = success -> 
		1:(s_whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface' = fakeStart);
	// Transition to synchronize the fail return when invoked by node 4 from module whoisOperation_GuiInterface__guiComponentPC_Provided_GuiInterface
	[ret_whoisOperation_GuiInterface__guiComponentPC_Provided_GuiInterface_4_whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface] s_whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface = fail -> 
		1:(s_whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface' = fail);
	
	// Transitions from node  :
	// 
	[]s_whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface = 3 ->
		1.0:(s_whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface' = 4);




	// Invocation transition to module whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface
	[call_whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface_4_whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface] s_whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface = 4 -> 
		1:(s_whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface' = 6);
	// Success return transition from module whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface
	[ret_whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface_4_whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface] s_whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface = 6 & s_whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface = success -> 
		1:(s_whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface' = 5);
	// Fail return transition from module whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface
	[ret_whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface_4_whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface] s_whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface = 6 & s_whoisOperation_DataRetriever__dataRetrieverPC_Provided_DataRetrieverInterface = fail -> 
		1:(s_whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface' = fail);


	// Transition from end node  to success
	[] s_whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface = 5 -> 1:(s_whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface' = success);
	// Transition to fix deadlocks on fake start state
	[] s_whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface = fakeStart -> 1:(s_whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface' = fakeStart);
	
	// Transition to fix deadlocks on fail state
	[] s_whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface = fail -> 1:(s_whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface' = fail);

endmodule

module whoisOperation_GuiInterface__guiComponentPC_Provided_GuiInterface
	s_whoisOperation_GuiInterface__guiComponentPC_Provided_GuiInterface:[0..6] init fakeStart;
	// Transition to start module when invoked by node 4 from module whoisOperation_GuiInterface__clientComposite_Provided_GuiInterface__join__guiComponentPC_Provided_GuiInterface
	[call_whoisOperation_GuiInterface__clientComposite_Provided_GuiInterface__join__guiComponentPC_Provided_GuiInterface_4_whoisOperation_GuiInterface__guiComponentPC_Provided_GuiInterface] s_whoisOperation_GuiInterface__guiComponentPC_Provided_GuiInterface = fakeStart -> 
		1:(s_whoisOperation_GuiInterface__guiComponentPC_Provided_GuiInterface' = 3);
	// Transition to synchronize the successful return when invoked by node 4 from module whoisOperation_GuiInterface__clientComposite_Provided_GuiInterface__join__guiComponentPC_Provided_GuiInterface
	[ret_whoisOperation_GuiInterface__clientComposite_Provided_GuiInterface__join__guiComponentPC_Provided_GuiInterface_4_whoisOperation_GuiInterface__guiComponentPC_Provided_GuiInterface] s_whoisOperation_GuiInterface__guiComponentPC_Provided_GuiInterface = success -> 
		1:(s_whoisOperation_GuiInterface__guiComponentPC_Provided_GuiInterface' = fakeStart);
	// Transition to synchronize the fail return when invoked by node 4 from module whoisOperation_GuiInterface__clientComposite_Provided_GuiInterface__join__guiComponentPC_Provided_GuiInterface
	[ret_whoisOperation_GuiInterface__clientComposite_Provided_GuiInterface__join__guiComponentPC_Provided_GuiInterface_4_whoisOperation_GuiInterface__guiComponentPC_Provided_GuiInterface] s_whoisOperation_GuiInterface__guiComponentPC_Provided_GuiInterface = fail -> 
		1:(s_whoisOperation_GuiInterface__guiComponentPC_Provided_GuiInterface' = fail);
	
	// Transitions from node start :
	// 
	[]s_whoisOperation_GuiInterface__guiComponentPC_Provided_GuiInterface = 3 ->
		1.0:(s_whoisOperation_GuiInterface__guiComponentPC_Provided_GuiInterface' = 4);




	// Invocation transition to module whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface
	[call_whoisOperation_GuiInterface__guiComponentPC_Provided_GuiInterface_4_whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface] s_whoisOperation_GuiInterface__guiComponentPC_Provided_GuiInterface = 4 -> 
		1:(s_whoisOperation_GuiInterface__guiComponentPC_Provided_GuiInterface' = 6);
	// Success return transition from module whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface
	[ret_whoisOperation_GuiInterface__guiComponentPC_Provided_GuiInterface_4_whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface] s_whoisOperation_GuiInterface__guiComponentPC_Provided_GuiInterface = 6 & s_whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface = success -> 
		1:(s_whoisOperation_GuiInterface__guiComponentPC_Provided_GuiInterface' = 5);
	// Fail return transition from module whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface
	[ret_whoisOperation_GuiInterface__guiComponentPC_Provided_GuiInterface_4_whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface] s_whoisOperation_GuiInterface__guiComponentPC_Provided_GuiInterface = 6 & s_whoisOperation_DataRetriever__guiComponentPC_Required_DataRetrieverInterface__join__dataRetrieverPC_Provided_DataRetrieverInterface = fail -> 
		1:(s_whoisOperation_GuiInterface__guiComponentPC_Provided_GuiInterface' = fail);


	// Transition from end node end to success
	[] s_whoisOperation_GuiInterface__guiComponentPC_Provided_GuiInterface = 5 -> 1:(s_whoisOperation_GuiInterface__guiComponentPC_Provided_GuiInterface' = success);
	// Transition to fix deadlocks on fake start state
	[] s_whoisOperation_GuiInterface__guiComponentPC_Provided_GuiInterface = fakeStart -> 1:(s_whoisOperation_GuiInterface__guiComponentPC_Provided_GuiInterface' = fakeStart);
	
	// Transition to fix deadlocks on fail state
	[] s_whoisOperation_GuiInterface__guiComponentPC_Provided_GuiInterface = fail -> 1:(s_whoisOperation_GuiInterface__guiComponentPC_Provided_GuiInterface' = fail);

endmodule

